version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test
      MYSQL_USER: testuser
      MYSQL_PASSWORD: secret